#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
08_make_supplementary_performance_figures.py

Create publication-ready supplementary performance figures from the revised
Stage-03 predictions and Stage-07 patient-level bootstrap outputs.

This stage performs no model fitting, tuning, calibration fitting, or
resampling. Mortality figures use the calibrated probabilities generated by
03_train_xgboost.py; patients with unknown mortality outcome are excluded from
mortality discrimination/calibration plots, consistent with Stage 07.

Primary displayed representations are Full and Static. Full is structurally
unavailable at 1 h in the revised tensor design, so the 1-h Full point is
intentionally absent rather than imputed or copied from another channel.

Outputs
-------
S1_extended_mortality_trajectories.{png,pdf,svg}
S2_extended_los_trajectories.{png,pdf,svg}
S3_mortality_discrimination_24h.{png,pdf,svg}
S4_mortality_calibration_24h.{png,pdf,svg}
S5_los_observed_vs_predicted_24h.{png,pdf,svg}
08_supplementary_figures_manifest.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from matplotlib.lines import Line2D
from sklearn.metrics import (
    average_precision_score,
    precision_recall_curve,
    roc_auc_score,
    roc_curve,
)


DEFAULT_MODELING_ROOT = Path("/home/ddimopoulos/Paper_05_Tensor/01_Modeling")

LANDMARKS = [1, 4, 8, 12, 16, 20, 24, 36, 48]
VARIANTS = ["full", "static"]
COHORTS = ["mimic_test", "eicu_external"]

COHORT_LABEL = {
    "mimic_test": "MIMIC-IV internal test",
    "eicu_external": "eICU-CRD external",
}

VARIANT_LABEL = {
    "full": "Full",
    "static": "Static",
}

COLORS = {
    "full": "#1f77b4",      # blue
    "static": "#ff7f0e",    # orange
    "reference": "#666666", # neutral gray
}


# ---------------------------------------------------------------------
# Basic helpers
# ---------------------------------------------------------------------
def configure_matplotlib() -> None:
    plt.rcParams.update(
        {
            "font.size": 9,
            "axes.titlesize": 10,
            "axes.labelsize": 9,
            "legend.fontsize": 8,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "figure.dpi": 120,
            "savefig.dpi": 600,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.linewidth": 0.8,
            "grid.alpha": 0.20,
        }
    )


def save_all(fig, output_dir: Path, stem: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(output_dir / f"{stem}.png", dpi=600, bbox_inches="tight")
    fig.savefig(output_dir / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(output_dir / f"{stem}.svg", bbox_inches="tight")
    plt.close(fig)


def add_panel_label(ax, label: str) -> None:
    ax.text(
        -0.13,
        1.04,
        label,
        transform=ax.transAxes,
        fontsize=10,
        fontweight="bold",
        va="bottom",
        ha="left",
    )


def prediction_path(
    modeling_root: Path,
    landmark: int,
    outcome: str,
    variant: str,
    cohort: str,
) -> Path:
    return (
        modeling_root
        / "results"
        / f"landmark_{landmark:03d}h"
        / outcome
        / variant
        / f"predictions_{cohort}.parquet"
    )


def load_prediction(
    modeling_root: Path,
    landmark: int,
    outcome: str,
    variant: str,
    cohort: str,
) -> pd.DataFrame:
    path = prediction_path(modeling_root, landmark, outcome, variant, cohort)
    if not path.is_file():
        raise FileNotFoundError(path)

    df = pd.read_parquet(path)
    required_common = {"patient_id", "stay_id", "y_true"}
    missing = required_common.difference(df.columns)
    if missing:
        raise ValueError(f"{path} missing columns: {sorted(missing)}")

    if df["patient_id"].astype(str).duplicated().any():
        raise ValueError(f"{path}: duplicate patient_id rows detected.")

    if outcome == "mortality":
        required = {"prediction_calibrated"}
        missing = required.difference(df.columns)
        if missing:
            raise ValueError(f"{path} missing columns: {sorted(missing)}")

        out = df[["patient_id", "stay_id", "y_true", "prediction_calibrated"]].copy()
        out["y_true"] = pd.to_numeric(out["y_true"], errors="coerce")
        out["prediction_calibrated"] = pd.to_numeric(
            out["prediction_calibrated"], errors="coerce"
        )

        # eICU patients with unknown hospital outcome remain in prediction files
        # but are not evaluable for mortality metrics/plots.
        known = (
            np.isfinite(out["y_true"].to_numpy(dtype=float))
            & np.isfinite(out["prediction_calibrated"].to_numpy(dtype=float))
        )
        out = out.loc[known].copy()

        if out.empty:
            raise ValueError(f"{path}: no mortality-known rows available.")
        labels = set(out["y_true"].astype(int).unique().tolist())
        if not labels.issubset({0, 1}):
            raise ValueError(f"{path}: non-binary mortality labels: {sorted(labels)}")
        if ((out["prediction_calibrated"] < 0) | (out["prediction_calibrated"] > 1)).any():
            raise ValueError(f"{path}: calibrated probabilities outside [0,1].")

        return out.reset_index(drop=True)

    if outcome == "los":
        required = {"prediction"}
        missing = required.difference(df.columns)
        if missing:
            raise ValueError(f"{path} missing columns: {sorted(missing)}")

        out = df[["patient_id", "stay_id", "y_true", "prediction"]].copy()
        out["y_true"] = pd.to_numeric(out["y_true"], errors="raise")
        out["prediction"] = pd.to_numeric(out["prediction"], errors="raise")
        finite = (
            np.isfinite(out["y_true"].to_numpy(dtype=float))
            & np.isfinite(out["prediction"].to_numpy(dtype=float))
        )
        if not finite.all():
            raise ValueError(f"{path}: non-finite LOS target/prediction rows.")
        if (out["y_true"] <= 0).any():
            raise ValueError(f"{path}: remaining LOS target must be > 0.")
        return out.reset_index(drop=True)

    raise ValueError(f"Unknown outcome: {outcome}")


def load_bootstrap_ci(modeling_root: Path) -> tuple[pd.DataFrame, dict]:
    bootstrap_dir = modeling_root / "bootstrap_results"
    path = bootstrap_dir / "bootstrap_metric_ci.csv"
    manifest_path = bootstrap_dir / "bootstrap_run_manifest.json"

    if not path.is_file():
        raise FileNotFoundError(
            f"{path}\nMissing bootstrap_metric_ci.csv under bootstrap_results."
        )
    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"{manifest_path}\nMissing Stage-07 bootstrap manifest."
        )

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if int(manifest.get("bootstrap_replicates", -1)) < 100:
        raise ValueError("Invalid bootstrap replicate count in Stage-07 manifest.")
    if manifest.get("mortality_probability") != "calibrated":
        raise ValueError(
            "Supplementary mortality figures require calibrated probabilities, "
            "but Stage-07 manifest is not calibrated."
        )

    df = pd.read_csv(path)
    required = {
        "metric",
        "estimate",
        "ci_low",
        "ci_high",
        "landmark_hour",
        "outcome",
        "variant",
        "cohort",
        "n",
        "valid_bootstrap_replicates",
    }
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"bootstrap_metric_ci.csv missing columns: {sorted(missing)}")

    key = ["landmark_hour", "outcome", "variant", "cohort", "metric"]
    if df.duplicated(key).any():
        dup = df.loc[df.duplicated(key, keep=False), key]
        raise ValueError(
            "Duplicate bootstrap metric rows detected:\n"
            + dup.to_string(index=False)
        )

    numeric_cols = ["estimate", "ci_low", "ci_high"]
    if not np.isfinite(df[numeric_cols].to_numpy(dtype=float)).all():
        raise ValueError("Non-finite bootstrap estimates/CIs detected.")

    return df, manifest


# ---------------------------------------------------------------------
# Smart legend placement
# ---------------------------------------------------------------------
def _count_points_inside_bbox(points_disp: np.ndarray, bbox) -> int:
    if points_disp is None or len(points_disp) == 0:
        return 0
    x = points_disp[:, 0]
    y = points_disp[:, 1]
    inside = (
        (x >= bbox.x0) & (x <= bbox.x1) &
        (y >= bbox.y0) & (y <= bbox.y1)
    )
    return int(np.sum(inside))


def _collect_display_points(ax):
    pts_all = []

    # Lines
    for line in ax.lines:
        try:
            x = np.asarray(line.get_xdata(), dtype=float)
            y = np.asarray(line.get_ydata(), dtype=float)
        except Exception:
            continue
        m = np.isfinite(x) & np.isfinite(y)
        if np.any(m):
            pts = np.column_stack([x[m], y[m]])
            pts_all.append(ax.transData.transform(pts))

    # Scatter / errorbar collections / hexbin
    for coll in ax.collections:
        try:
            offsets = coll.get_offsets()
            if offsets is None:
                continue
            offsets = np.asarray(offsets, dtype=float)
            if offsets.ndim == 2 and offsets.shape[1] == 2 and len(offsets) > 0:
                m = np.isfinite(offsets[:, 0]) & np.isfinite(offsets[:, 1])
                if np.any(m):
                    pts_all.append(ax.transData.transform(offsets[m]))
        except Exception:
            continue

    if not pts_all:
        return np.empty((0, 2))
    return np.vstack(pts_all)


def place_legend_smart(ax, handles=None, labels=None, **legend_kwargs):
    """
    Try multiple legend positions and select the one with minimum overlap
    with plotted content in display coordinates.
    """
    fig = ax.figure
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()

    if handles is None or labels is None:
        handles, labels = ax.get_legend_handles_labels()

    if not handles:
        return None

    candidate_locs = [
        "upper right",
        "upper left",
        "lower left",
        "lower right",
        "center left",
        "center right",
        "upper center",
        "lower center",
    ]

    plotted_points = _collect_display_points(ax)

    best_loc = None
    best_score = None

    for loc in candidate_locs:
        tmp_leg = ax.legend(
            handles,
            labels,
            loc=loc,
            frameon=True,
            fancybox=True,
            framealpha=0.90,
            borderpad=0.35,
            handlelength=2.0,
            **legend_kwargs,
        )
        fig.canvas.draw()
        bbox = tmp_leg.get_window_extent(renderer=renderer).expanded(1.03, 1.08)

        score = _count_points_inside_bbox(plotted_points, bbox)

        # Mild penalty for very central locations
        if "center" in loc:
            score += 3

        tmp_leg.remove()

        if best_score is None or score < best_score:
            best_score = score
            best_loc = loc

    final_leg = ax.legend(
        handles,
        labels,
        loc=best_loc if best_loc is not None else "best",
        frameon=True,
        fancybox=True,
        framealpha=0.90,
        borderpad=0.35,
        handlelength=2.0,
        **legend_kwargs,
    )
    return final_leg


# ---------------------------------------------------------------------
# Metric helpers
# ---------------------------------------------------------------------
METRIC_ALIASES = {
    "average_precision": ["average_precision", "ap"],
    "brier": ["brier", "brier_score"],
    "roc_auc": ["roc_auc", "auroc"],
    "mae": ["mae"],
    "rmse": ["rmse"],
}


def metric_mask(df: pd.DataFrame, metric_name: str) -> pd.Series:
    candidates = METRIC_ALIASES.get(metric_name, [metric_name])
    return df["metric"].isin(candidates)


def find_ci(
    ci: pd.DataFrame,
    *,
    landmark: int,
    outcome: str,
    variant: str,
    cohort: str,
    metric: str,
):
    row = ci.loc[
        ci["landmark_hour"].eq(landmark)
        & ci["outcome"].eq(outcome)
        & ci["variant"].eq(variant)
        & ci["cohort"].eq(cohort)
        & metric_mask(ci, metric)
    ]
    if row.empty:
        return None
    if len(row) != 1:
        raise ValueError(
            f"Expected one bootstrap CI row for "
            f"{landmark}h/{outcome}/{variant}/{cohort}/{metric}, found {len(row)}."
        )
    r = row.iloc[0]
    return float(r["estimate"]), float(r["ci_low"]), float(r["ci_high"])


# ---------------------------------------------------------------------
# Plot utilities
# ---------------------------------------------------------------------
def plot_trajectory_panel(
    ax,
    ci: pd.DataFrame,
    *,
    outcome: str,
    cohort: str,
    metric: str,
    ylabel: str,
    title: str,
):
    data = ci.loc[
        ci["outcome"].eq(outcome)
        & ci["cohort"].eq(cohort)
        & ci["variant"].isin(VARIANTS)
        & metric_mask(ci, metric)
    ].copy()

    for variant in VARIANTS:
        g = data.loc[data["variant"].eq(variant)].sort_values("landmark_hour")
        if g.empty:
            continue

        x = g["landmark_hour"].to_numpy(dtype=float)
        y = g["estimate"].to_numpy(dtype=float)
        lo = g["ci_low"].to_numpy(dtype=float)
        hi = g["ci_high"].to_numpy(dtype=float)

        ax.plot(
            x,
            y,
            marker="o",
            linewidth=1.7,
            markersize=4.5,
            color=COLORS[variant],
            label=VARIANT_LABEL[variant],
        )
        ax.fill_between(
            x,
            lo,
            hi,
            alpha=0.14,
            color=COLORS[variant],
            linewidth=0,
        )

    ax.set_title(title)
    ax.set_xlabel("Landmark hour")
    ax.set_ylabel(ylabel)
    ax.set_xticks(LANDMARKS)
    ax.grid(True)
    place_legend_smart(ax)


# ---------------------------------------------------------------------
# Figure S1: Mortality trajectories
# ---------------------------------------------------------------------
def figure_s1_mortality_trajectories(ci: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(7.2, 6.0), sharex=True)

    specs = [
        (0, 0, "mimic_test", "average_precision", "Average precision", "Average precision — MIMIC-IV"),
        (0, 1, "eicu_external", "average_precision", "Average precision", "Average precision — eICU-CRD"),
        (1, 0, "mimic_test", "brier", "Brier score", "Brier score — MIMIC-IV"),
        (1, 1, "eicu_external", "brier", "Brier score", "Brier score — eICU-CRD"),
    ]

    for idx, (r, c, cohort, metric, ylabel, title) in enumerate(specs):
        plot_trajectory_panel(
            axes[r, c],
            ci,
            outcome="mortality",
            cohort=cohort,
            metric=metric,
            ylabel=ylabel,
            title=title,
        )
        add_panel_label(axes[r, c], f"({chr(ord('a') + idx)})")

    save_all(fig, output_dir, "S1_extended_mortality_trajectories")


# ---------------------------------------------------------------------
# Figure S2: LOS trajectories
# ---------------------------------------------------------------------
def figure_s2_los_trajectories(ci: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(7.2, 6.0), sharex=True)

    specs = [
        (0, 0, "mimic_test", "mae", "MAE (days)", "MAE — MIMIC-IV"),
        (0, 1, "eicu_external", "mae", "MAE (days)", "MAE — eICU-CRD"),
        (1, 0, "mimic_test", "rmse", "RMSE (days)", "RMSE — MIMIC-IV"),
        (1, 1, "eicu_external", "rmse", "RMSE (days)", "RMSE — eICU-CRD"),
    ]

    for idx, (r, c, cohort, metric, ylabel, title) in enumerate(specs):
        plot_trajectory_panel(
            axes[r, c],
            ci,
            outcome="los",
            cohort=cohort,
            metric=metric,
            ylabel=ylabel,
            title=title,
        )
        add_panel_label(axes[r, c], f"({chr(ord('a') + idx)})")

    save_all(fig, output_dir, "S2_extended_los_trajectories")


# ---------------------------------------------------------------------
# Figure S3: 24h mortality ROC + PR
# ---------------------------------------------------------------------
def figure_s3_discrimination(
    modeling_root: Path,
    ci: pd.DataFrame,
    output_dir: Path,
    landmark: int = 24,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(7.4, 6.2))

    for col, cohort in enumerate(COHORTS):
        prevalence = None

        # ROC
        roc_handles = []
        roc_labels = []

        for variant in VARIANTS:
            pred = load_prediction(modeling_root, landmark, "mortality", variant, cohort)
            y = pred["y_true"].to_numpy(dtype=int)
            p = pred["prediction_calibrated"].to_numpy(dtype=float)

            prevalence = float(np.mean(y))

            fpr, tpr, _ = roc_curve(y, p)
            auc_ci = find_ci(
                ci,
                landmark=landmark,
                outcome="mortality",
                variant=variant,
                cohort=cohort,
                metric="roc_auc",
            )
            if auc_ci is None:
                auc_val = roc_auc_score(y, p)
                label = f"{VARIANT_LABEL[variant]}: {auc_val:.3f}"
            else:
                label = f"{VARIANT_LABEL[variant]}: {auc_ci[0]:.3f} [{auc_ci[1]:.3f}-{auc_ci[2]:.3f}]"

            line, = axes[0, col].plot(
                fpr,
                tpr,
                linewidth=1.7,
                color=COLORS[variant],
                label=label,
            )
            roc_handles.append(line)
            roc_labels.append(label)

        ref_line, = axes[0, col].plot(
            [0, 1],
            [0, 1],
            linestyle="--",
            linewidth=1.1,
            color=COLORS["reference"],
            label="Reference",
        )
        roc_handles.append(ref_line)
        roc_labels.append("Reference")

        axes[0, col].set_xlim(0, 1)
        axes[0, col].set_ylim(0, 1.02)
        axes[0, col].set_xlabel("False-positive rate")
        axes[0, col].set_ylabel("True-positive rate")
        axes[0, col].set_title(f"ROC — {COHORT_LABEL[cohort]}")
        axes[0, col].grid(True)
        place_legend_smart(axes[0, col], handles=roc_handles, labels=roc_labels)

        # PR
        pr_handles = []
        pr_labels = []

        for variant in VARIANTS:
            pred = load_prediction(modeling_root, landmark, "mortality", variant, cohort)
            y = pred["y_true"].to_numpy(dtype=int)
            p = pred["prediction_calibrated"].to_numpy(dtype=float)

            precision, recall, _ = precision_recall_curve(y, p)
            ap_ci = find_ci(
                ci,
                landmark=landmark,
                outcome="mortality",
                variant=variant,
                cohort=cohort,
                metric="average_precision",
            )
            if ap_ci is None:
                ap_val = average_precision_score(y, p)
                label = f"{VARIANT_LABEL[variant]}: {ap_val:.3f}"
            else:
                label = f"{VARIANT_LABEL[variant]}: {ap_ci[0]:.3f} [{ap_ci[1]:.3f}-{ap_ci[2]:.3f}]"

            line, = axes[1, col].plot(
                recall,
                precision,
                linewidth=1.7,
                color=COLORS[variant],
                label=label,
            )
            pr_handles.append(line)
            pr_labels.append(label)

        prev_line = axes[1, col].axhline(
            prevalence,
            linestyle="--",
            linewidth=1.1,
            color=COLORS["reference"],
            label=f"Prevalence: {prevalence:.3f}",
        )
        pr_handles.append(prev_line)
        pr_labels.append(f"Prevalence: {prevalence:.3f}")

        axes[1, col].set_xlim(0, 1)
        axes[1, col].set_ylim(0, 1.02)
        axes[1, col].set_xlabel("Recall")
        axes[1, col].set_ylabel("Precision")
        axes[1, col].set_title(f"Precision–recall — {COHORT_LABEL[cohort]}")
        axes[1, col].grid(True)
        place_legend_smart(axes[1, col], handles=pr_handles, labels=pr_labels)

    for idx, ax in enumerate(axes.flat):
        add_panel_label(ax, f"({chr(ord('a') + idx)})")

    save_all(fig, output_dir, "S3_mortality_discrimination_24h")


# ---------------------------------------------------------------------
# Calibration helpers
# ---------------------------------------------------------------------
def wilson_interval(k, n, z=1.959963984540054):
    if n <= 0:
        return np.nan, np.nan
    phat = k / n
    denom = 1.0 + z * z / n
    centre = (phat + z * z / (2.0 * n)) / denom
    half = (
        z
        * np.sqrt(phat * (1.0 - phat) / n + z * z / (4.0 * n * n))
        / denom
    )
    return centre - half, centre + half


def quantile_calibration_points(y: np.ndarray, p: np.ndarray, n_bins: int = 10) -> pd.DataFrame:
    frame = pd.DataFrame({"y": y.astype(int), "p": p.astype(float)})
    frame["bin"] = pd.qcut(frame["p"], q=n_bins, duplicates="drop")

    rows = []
    for _, g in frame.groupby("bin", observed=True, sort=True):
        n = int(len(g))
        k = int(g["y"].sum())
        obs = float(g["y"].mean())
        pred = float(g["p"].mean())
        lo, hi = wilson_interval(k, n)
        rows.append(
            {
                "mean_predicted": pred,
                "observed": obs,
                "ci_low": lo,
                "ci_high": hi,
                "n": n,
            }
        )

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------
# Figure S4: 24h calibration
# ---------------------------------------------------------------------
def figure_s4_calibration(
    modeling_root: Path,
    output_dir: Path,
    landmark: int = 24,
) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.5), sharex=True, sharey=True)

    for col, cohort in enumerate(COHORTS):
        ax = axes[col]

        ref, = ax.plot(
            [0, 1],
            [0, 1],
            linestyle="--",
            linewidth=1.1,
            color=COLORS["reference"],
            label="Ideal calibration",
        )

        handles = [ref]
        labels = ["Ideal calibration"]

        for variant in VARIANTS:
            pred = load_prediction(modeling_root, landmark, "mortality", variant, cohort)
            y = pred["y_true"].to_numpy(dtype=int)
            p = pred["prediction_calibrated"].to_numpy(dtype=float)

            cal = quantile_calibration_points(y, p, n_bins=10)
            yerr = np.vstack(
                [
                    cal["observed"].to_numpy() - cal["ci_low"].to_numpy(),
                    cal["ci_high"].to_numpy() - cal["observed"].to_numpy(),
                ]
            )

            eb = ax.errorbar(
                cal["mean_predicted"],
                cal["observed"],
                yerr=yerr,
                marker="o",
                markersize=4.5,
                linewidth=1.5,
                capsize=2.5,
                color=COLORS[variant],
                label=VARIANT_LABEL[variant],
            )
            handles.append(eb)
            labels.append(VARIANT_LABEL[variant])

        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_xlabel("Mean predicted probability")
        ax.set_ylabel("Observed event frequency")
        ax.set_title(COHORT_LABEL[cohort])
        ax.grid(axis="both", alpha=0.20)
        place_legend_smart(ax, handles=handles, labels=labels)
        add_panel_label(ax, f"({chr(ord('a') + col)})")

    save_all(fig, output_dir, "S4_mortality_calibration_24h")


# ---------------------------------------------------------------------
# Figure S5: 24h LOS observed vs predicted
# ---------------------------------------------------------------------
def figure_s5_los_observed_predicted(
    modeling_root: Path,
    output_dir: Path,
    landmark: int = 24,
    gridsize: int = 45,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(7.3, 6.5), sharex=True, sharey=True)

    all_limits = []
    loaded = {}

    for row, variant in enumerate(VARIANTS):
        for col, cohort in enumerate(COHORTS):
            pred = load_prediction(modeling_root, landmark, "los", variant, cohort)
            loaded[(variant, cohort)] = pred

            y = pred["y_true"].to_numpy(dtype=float)
            p = pred["prediction"].to_numpy(dtype=float)

            all_limits.extend(
                [
                    float(np.nanmin(y)),
                    float(np.nanmax(y)),
                    float(np.nanmin(p)),
                    float(np.nanmax(p)),
                ]
            )

    lo = min(all_limits)
    hi = max(all_limits)

    for row, variant in enumerate(VARIANTS):
        for col, cohort in enumerate(COHORTS):
            ax = axes[row, col]
            pred = loaded[(variant, cohort)]

            y = pred["y_true"].to_numpy(dtype=float)
            p = pred["prediction"].to_numpy(dtype=float)

            hb = ax.hexbin(
                y,
                p,
                gridsize=gridsize,
                mincnt=1,
                cmap="Blues",
                linewidths=0,
            )

            ref_line, = ax.plot(
                [lo, hi],
                [lo, hi],
                linestyle="--",
                linewidth=1.1,
                color=COLORS["reference"],
                label="Identity",
            )

            ax.set_xlim(lo, hi)
            ax.set_ylim(lo, hi)
            ax.set_xlabel("Observed remaining ICU LOS (days)")
            ax.set_ylabel("Predicted remaining ICU LOS (days)")
            ax.set_title(f"{VARIANT_LABEL[variant]} — {COHORT_LABEL[cohort]}")
            ax.grid(axis="both", alpha=0.20)

            handles = [ref_line]
            labels = ["Identity"]
            place_legend_smart(ax, handles=handles, labels=labels)

            idx = row * 2 + col
            add_panel_label(ax, f"({chr(ord('a') + idx)})")

    save_all(fig, output_dir, "S5_los_observed_vs_predicted_24h")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------
def make_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--modeling-root",
        type=Path,
        default=DEFAULT_MODELING_ROOT,
        help="Path to Paper_05_Tensor/01_Modeling",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Default: <modeling-root>/figures/supplementary_composite",
    )
    return parser


def main() -> int:
    args = make_parser().parse_args()

    modeling_root = args.modeling_root.expanduser().resolve()
    if not modeling_root.is_dir():
        raise FileNotFoundError(modeling_root)

    output_dir = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else modeling_root / "figures" / "supplementary_composite"
    )

    configure_matplotlib()
    ci, bootstrap_manifest = load_bootstrap_ci(modeling_root)

    selected_ci = ci.loc[
        ci["variant"].isin(VARIANTS)
        & ci["cohort"].isin(COHORTS)
        & ci["landmark_hour"].isin(LANDMARKS)
    ].copy()
    output_dir.mkdir(parents=True, exist_ok=True)
    selected_ci.to_csv(
        output_dir / "08_supplementary_trajectory_data.csv",
        index=False,
    )

    figure_s1_mortality_trajectories(ci, output_dir)
    figure_s2_los_trajectories(ci, output_dir)
    figure_s3_discrimination(modeling_root, ci, output_dir, landmark=24)
    figure_s4_calibration(modeling_root, output_dir, landmark=24)
    figure_s5_los_observed_predicted(modeling_root, output_dir, landmark=24)

    manifest = {
        "script": Path(__file__).name,
        "modeling_root": str(modeling_root),
        "output_dir": str(output_dir),
        "representations": VARIANTS,
        "cohorts": COHORTS,
        "landmarks": LANDMARKS,
        "anchor_landmark_hour": 24,
        "mortality_probability": "prediction_calibrated",
        "mortality_unknown_outcomes_excluded": True,
        "bootstrap_replicates": int(
            bootstrap_manifest.get("bootstrap_replicates", -1)
        ),
        "bootstrap_ci_percent": float(
            bootstrap_manifest.get("ci_percent", float("nan"))
        ),
        "notes": [
            "Full is structurally unavailable at 1 h; no Full 1-h point is imputed.",
            "Mortality ROC/PR/calibration plots exclude patients with unknown y_true.",
            "No model fitting, tuning, calibration fitting, or bootstrap resampling occurs in this stage.",
        ],
        "outputs": [
            "S1_extended_mortality_trajectories",
            "S2_extended_los_trajectories",
            "S3_mortality_discrimination_24h",
            "S4_mortality_calibration_24h",
            "S5_los_observed_vs_predicted_24h",
            "08_supplementary_trajectory_data.csv",
        ],
        "status": "PASS",
    }
    (output_dir / "08_supplementary_figures_manifest.json").write_text(
        json.dumps(manifest, indent=2),
        encoding="utf-8",
    )

    print(f"Supplementary composite figures written to: {output_dir}")
    print("PASS: Stage 08 supplementary figures complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())